apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  labels:
    app: userprofile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
       containers:
       - name: userprofile
         image: registryvpc6526.azurecr.io/tripinsights/userprofile:1.0
         ports:
         - containerPort: 80